import { 
    Check, 
    Heart, 
    Footprints, 
    UserCheck, 
    Bike, 
    Waves, 
    Brain, 
    Mountain, 
    Activity, 
    Clock,
    Dumbbell,
    Cigarette,
    CigaretteOff,
    Coffee,
    Book,
    Moon,
    Smartphone,
    Utensils,
    Car,
    Dog,
    TreePine,
    Camera,
    Music,
    Palette,
    Code,
    Gamepad2,
    Phone,
    Mail,
    MessageCircle,
    ShoppingCart,
    Home,
    Plane,
    Map,
    Calendar,
    Star,
    Award,
    Target,
    Trophy,
    Gift,
    Lightbulb,
    Zap,
    Sun,
    CloudRain,
    Thermometer,
    Wind,
    Leaf,
    Flower,
    Sparkles,
    Flame,
    Droplets,
    Snowflake,
    Sunrise,
    Sunset
} from "lucide-react";

export const TASK_ICONS = {
    check: Check,
    heart: Heart,
    footprints: Footprints,
    "user-check": UserCheck,
    bike: Bike,
    waves: Waves,
    brain: Brain,
    mountain: Mountain,
    activity: Activity,
    clock: Clock,
    dumbbell: Dumbbell,
    cigarette: Cigarette,
    "cigarette-off": CigaretteOff,
    coffee: Coffee,
    book: Book,
    moon: Moon,
    smartphone: Smartphone,
    utensils: Utensils,
    car: Car,
    dog: Dog,
    "tree-pine": TreePine,
    camera: Camera,
    music: Music,
    palette: Palette,
    code: Code,
    gamepad2: Gamepad2,
    phone: Phone,
    mail: Mail,
    "message-circle": MessageCircle,
    "shopping-cart": ShoppingCart,
    home: Home,
    plane: Plane,
    map: Map,
    calendar: Calendar,
    star: Star,
    award: Award,
    target: Target,
    trophy: Trophy,
    gift: Gift,
    lightbulb: Lightbulb,
    zap: Zap,
    sun: Sun,
    "cloud-rain": CloudRain,
    thermometer: Thermometer,
    wind: Wind,
    leaf: Leaf,
    flower: Flower,
    sparkles: Sparkles,
    flame: Flame,
    droplets: Droplets,
    snowflake: Snowflake,
    sunrise: Sunrise,
    sunset: Sunset,
};

export const TASK_COLORS = {
    primary: {
        bg: "bg-gradient-to-br from-orange-400 to-pink-500",
        text: "text-white",
    },
    purple: {
        bg: "bg-gradient-to-br from-purple-500 to-purple-700",
        text: "text-white",
    },
    teal: {
        bg: "bg-gradient-to-br from-teal-400 to-cyan-500",
        text: "text-white",
    },
    green: {
        bg: "bg-gradient-to-br from-green-400 to-emerald-500",
        text: "text-white",
    },
    yellow: {
        bg: "bg-gradient-to-br from-yellow-400 to-orange-500",
        text: "text-white",
    },
    blue: {
        bg: "bg-gradient-to-br from-blue-400 to-indigo-500",
        text: "text-white",
    },
    red: {
        bg: "bg-gradient-to-br from-red-400 to-rose-500",
        text: "text-white",
    },
    gray: {
        bg: "bg-gradient-to-br from-gray-400 to-gray-600",
        text: "text-white",
    },
    pink: {
        bg: "bg-gradient-to-br from-pink-400 to-rose-500",
        text: "text-white",
    },
    indigo: {
        bg: "bg-gradient-to-br from-indigo-400 to-purple-500",
        text: "text-white",
    },
};

export const HEALTH_TASKS = [
    {
        id: "walk",
        name: "♥ Walk or Run", 
        icon: Footprints,
        iconName: "footprints",
        color: "primary",
        type: "health",
        hasHealthData: true,
        defaultGoal: "5000",
        unit: "steps",
    },
    {
        id: "stand",
        name: "♥ Stand Minutes",
        icon: UserCheck,
        iconName: "user-check",
        color: "blue",
        type: "health",
        hasHealthData: true,
        defaultGoal: "12",
        unit: "hours",
    },
    {
        id: "cycle",
        name: "♥ Cycle",
        icon: Bike,
        iconName: "bike",
        color: "green",
        type: "health",
        hasHealthData: true,
        defaultGoal: "30",
        unit: "minutes",
    },
    {
        id: "swim",
        name: "♥ Swim",
        icon: Waves,
        iconName: "waves",
        color: "teal",
        type: "health",
        hasHealthData: true,
        defaultGoal: "20",
        unit: "minutes",
    },
    {
        id: "mindful",
        name: "⊕ Mindful Minutes",
        icon: Brain,
        iconName: "brain",
        color: "purple",
        type: "health",
        hasHealthData: true,
        defaultGoal: "10",
        unit: "minutes",
    },
    {
        id: "climb",
        name: "♥ Climb Flights",
        icon: Mountain,
        iconName: "mountain",
        color: "gray",
        type: "health",
        hasHealthData: true,
        defaultGoal: "10",
        unit: "flights",
    },
    {
        id: "activity",
        name: "♥ Activity Rings",
        icon: Activity,
        iconName: "activity",
        color: "red",
        type: "health",
        hasHealthData: true,
        defaultGoal: "3",
        unit: "rings",
    },
    {
        id: "standHours",
        name: "♥ Stand Hours",
        icon: Clock,
        iconName: "clock",
        color: "yellow",
        type: "health",
        hasHealthData: true,
        defaultGoal: "12",
        unit: "hours",
    },
    {
        id: "exercise",
        name: "♥ Exercise Minutes",
        icon: Dumbbell,
        iconName: "dumbbell",
        color: "indigo",
        type: "health",
        hasHealthData: true,
        defaultGoal: "30",
        unit: "minutes",
    },
];

export const SCHEDULE_OPTIONS = [
    { value: "daily", label: "Every Day" },
    { value: "weekdays", label: "Monday to Friday" },
    { value: "weekends", label: "Weekends Only" },
    { value: "custom", label: "Custom Days" },
    { value: "flexible", label: "X times per week" },
];
